version: '3.5'
services:
    web:
      # allow to debug inside image
      stdin_open: true
      tty: true
      container_name: my_line_web
      build: . # Location of our Dockerfile
      volumes: # Volume binding
        - './my_line_web:/usr/src/app' 
      ports: 
        - '4200:4200' # Port mapping
      command: > 
        bash -c "npm install && ng serve --host 0.0.0.0 --port 4200"